# Site settings
title: A tree, right when you needed one most
email: naurasj@moogmedia.ca
description: Collection of musings from Nauras Jabari's brain thingy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.timelytree.github.io" # the base hostname & protocol for your site
github_username:  timelytree
include: ["_pages", "_categories", "_demos"]
permalink: /:title

collections:
  category:
    output: true

# Build settings
markdown: kramdown
